### ISSUE TITLE
Kill LSG styles completely

### ISSUE THREAD

**Issue by joe-watkins** [hagenburger/livingstyleguide#117]
Hi great work on this tool!

I'd like to completely kill all LSG `.livingstyleguide--` styles that are injected into the html.. is that possible? Like a complete clean slate.

I'm finding them competing with the projects styles a bit.

**Comment by hagenburger** [comment]
Thanks, glad you enjoy it!

That is an interesting request :)
* how do they compete?
* Maybe there’s a bug?
* When those styles would be removed, how do you plan do style the style guide?

Right now, you can avoid them by just creating an empty file named `_livingstyleguide.scss` next to your the `styleguide.lsg` file.

**Comment by joe-watkins** [comment]
Hi thanks for the response. I'm seeing line-height/font-size competition.. mainly typography issues. I'm still testing on my end so it may be something I'm doing :) Thanks for the tip on the empty stylesheet..I'll try that.

**Comment by hagenburger** [comment]
@joe-watkins I guess this worked out? I’m closing this. Reopen it, if there is any issue left.
