### ISSUE TITLE
Markdown headers being output as raw text

### ISSUE THREAD

**Issue by soulpimp** [hagenburger/livingstyleguide#118]
I need to have more than two levels of heading for my style guide (h1 - h6). When I try to apply markdown for headings as ###heading, the result is '###heading' instead of an h3 tag.

Am I missing something?

**Comment by soulpimp** [comment]
Figured it out, was a spacing issue: ### heading, NOT ###heading

**Comment by hagenburger** [comment]
@soulpimp do you think this is worth to mention in the documentation? I think somebody else had the same issue before.

**Comment by soulpimp** [comment]
Hi Nico,

I do think it's worth mentioning as a lot of people (myself included) may
not know markdown well enough to know there are other heading options
outside of what is in your documentation.

Thanks.

C
