### ISSUE TITLE
Glob imports are not supported yet

### ISSUE THREAD

**Issue by stephanpavlovic** [hagenburger/livingstyleguide#38]
Currently no glob imports are supported

```
@import modules/*
```

Thanks in advance!

**Comment by hagenburger** [comment]
Globbing should work in [v2.0.0.alpha.3](https://github.com/hagenburger/livingstyleguide/releases/tag/v2.0.0.alpha.3) within Sass and when globbing for _*.lsg_ files (keep in mind: the automated importing of _*.lsg_ files for each _*.scss_ file is not upgraded into v2 yet).

**Comment by hagenburger** [comment]
Tested with _livingstyleguide_ [v2.0.0.alpha.3](https://github.com/hagenburger/livingstyleguide/releases/tag/v2.0.0.alpha.3), _rails_ 4.2.1, _sprockets-rails_ 2.2.4 and _sprockets_ 2.12.3 and it works well :)
