### ISSUE TITLE
output of multiple pages

### ISSUE THREAD

**Issue by ronaldlokers** [hagenburger/livingstyleguide#57]
I would like to be able to have multiple pages as output, so I can easily navigate/link to the different parts of code.

**Comment by hagenburger** [comment]
This is done and will be released and documented soon. Some examples can be found here: https://github.com/hagenburger/livingstyleguide-concept#c_new-multiple-pages-v20x

Basically you put all global configuration as well as header/footer HTML in a file named `_config.lsg`. Next you create all multiple pages (e. g. `index.html.lsg`, `components.html.lsg`, `layouts.html.lsg`, …) and start them with:

``` markdown
@import config

# Use Markdown to continue
```
