### ISSUE TITLE
Incorrect paths generated with asset path helpers using Living Style Guide with pre-release Compass, Rails 4

### ISSUE THREAD

**Issue by myabc** [hagenburger/livingstyleguide#70]
___

To reproduce:

1. Create a new Rails 4 project
    ```
    rails new example_project
   ```

2.  Add dependencies to `Gemfile`:
   ```ruby
   gem 'compass',          '1.0.0.alpha.19'
   gem 'livingstyleguide'
   ```

3. Add a basic `styleguide.html.lsg` to `/app/assets/`:
    ```
    # Base setup:
    source: application.css.sass
    title: "My Living Style Guide"
    ```

4. Add a basic `application.css.sass` that makes uses of font asset helpers, e.g.:
    ```sass
    @font-face
      font-family: "foobar"
      src: font-url('foobar/foobar.eot')
      src: font-url('foobar/foobar.eot?#iefix') format("embedded-opentype"), font-url('foobar/foobar.ttf') format("truetype"), font-url('foobar/foobar.svg#untitled-font-1') format("svg"), font-url('foobar/foobar.woff') format("woff")
      font-weight: normal
      font-style: normal
    
    body
      background-color: red
      font-family: foobar

    ```

**Expected:** fonts should be loaded from `/assets/foobar/foobar.woff`
**Actual:** browser attempts to load font files from `/fonts/foobar/foobar.woff`

**Comment by hagenburger** [comment]
I had a deep look into `sprockets`, `sprockets-rails`, `sass-rails`, `tilt`, and `middleman` which led into a complete refactoring. Having the new code, LSG should render Sass exactly the same way Rails/Middleman does and provide access to all helpers and load paths.

This will be available from 2.0.0.alpha.3 on.

**Comment by myabc** [comment]
@hagenburger great! Even though I'm thinking of eventually getting rid of Sprockets, parity with asset pipeline rendering would be fantastic.

**Comment by hagenburger** [comment]
If you don’t use Sprockets, it will fall back to [Tilt::ScssTemplate](https://github.com/rtomayko/tilt/blob/master/lib/tilt/sass.rb) for rendering. I would love to get feedback if it’s working for you. I’ve tested it on a Rails 4 and a Middleman project up till now.

If you want to have a quick test (but not upgrade your project yet):
* Use `gem "livingstyleguide", github: "hagenburger/livingstlyeguide", branch: "v2"`
* Create a `app/assets/stylesheets/test.html.lsg` containing `@import application.css.scss`
* Check the rendered CSS inside the HTML of <http://localhost:3000/assets/test.html>
